name: veinmind-tools-push
on:
  workflow_call:


jobs:
  push-veinmind-backdoor:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/python/veinmind-backdoor
      file: veinmind-backdoor

  push-veinmind-sensitive:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/python/veinmind-sensitive
      file: veinmind-sensitive

  push-veinmind-history:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/python/veinmind-history
      file: veinmind-history

  push-veinmind-malicious:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-malicious
      file: veinmind-malicious
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-weakpass:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-weakpass
      file: veinmind-weakpass
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-asset:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-asset
      file: veinmind-asset
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-webshell:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-webshell
      file: veinmind-webshell
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-unsafe-mount:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-unsafe-mount
      file: veinmind-unsafe-mount
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-log4j2:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-log4j2
      file: veinmind-log4j2
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-iac:
    uses: ./.github/workflows/push.yml
    with:
      path: ./plugins/go/veinmind-iac
      file: veinmind-iac
      CI_GOOS: linux
      CI_GOARCH: amd64

  push-veinmind-runner:
    uses: ./.github/workflows/push.yml
    needs: [push-veinmind-backdoor, push-veinmind-sensitive, push-veinmind-history, push-veinmind-malicious, push-veinmind-weakpass, push-veinmind-asset, push-veinmind-log4j2, push-veinmind-unsafe-mount, push-veinmind-iac]
    with:
      path: ./veinmind-runner
      file: veinmind-runner
      CI_GOOS: linux
      CI_GOARCH: amd64
