# entry
name: veinmind-tools
on: [push, pull_request]
jobs:
   package:
     uses: ./.github/workflows/veinmind-package.yml
   build:
     uses: ./.github/workflows/veinmind-build.yml
   push:
     uses: ./.github/workflows/veinmind-push.yml